# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'beshop.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(734, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 711, 481))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tabWidget.setStyleSheet("background-image:url(:/newPrefix/photop/eb8f6f18988140975da8553d15a8d25c.jpg);\n"
"\n"
"    font: 75 9pt \"Dubai\";\n"
"    color: #000;\n"
"    background-color: #fff;\n"
"    background-clip: border;\n"
"    border-image: none;\n"
"    border: 0px transparent black;\n"
"    outline: 0;\n"
"   font: Bold;\n"
"   font-family: Dubai;\n"
"opacity: 200;\n"
"   \n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.label_33 = QtWidgets.QLabel(self.tab_9)
        self.label_33.setGeometry(QtCore.QRect(290, 100, 221, 221))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("background-image:url(:/newPrefix/photop/download (1).png);\n"
"point-size: 13;\n"
"color: #fff;\n"
"font: 15pt;\n"
"font: Bold;\n"
"border: 2px solid #ea9cea;\n"
" border-radius: 70px 10px 520px 20px;")
        self.label_33.setText("")
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setWordWrap(False)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.tab_9)
        self.label_34.setGeometry(QtCore.QRect(360, 20, 261, 51))
        self.label_34.setStyleSheet("font: 15pt;\n"
"font: Bold;\n"
"font: MS Serif;\n"
"background: none;")
        self.label_34.setObjectName("label_34")
        self.tabWidget.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_10)
        self.groupBox_7.setGeometry(QtCore.QRect(20, 20, 441, 391))
        self.groupBox_7.setStyleSheet("background:none;")
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_35 = QtWidgets.QLabel(self.groupBox_7)
        self.label_35.setGeometry(QtCore.QRect(10, 40, 181, 161))
        self.label_35.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_35.setStyleSheet("background-image:url(:/newPrefix/photop/052b9c901d45e33b659dbedb7ee243c0.jpg);")
        self.label_35.setText("")
        self.label_35.setPixmap(QtGui.QPixmap(":/newPrefix/photop/052b9c901d45e33b659dbedb7ee243c0.jpg"))
        self.label_35.setScaledContents(True)
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.groupBox_7)
        self.label_36.setGeometry(QtCore.QRect(200, 40, 201, 161))
        self.label_36.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_36.setStyleSheet("background-image:url(:/newPrefix/photop/8d9cbf600f8a5749e42c8761f31f71d0.jpg);\n"
"")
        self.label_36.setText("")
        self.label_36.setPixmap(QtGui.QPixmap(":/newPrefix/photop/8d9cbf600f8a5749e42c8761f31f71d0.jpg"))
        self.label_36.setScaledContents(True)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.groupBox_7)
        self.label_37.setGeometry(QtCore.QRect(10, 220, 181, 161))
        self.label_37.setStyleSheet("background-image:url(:/newPrefix/photop/e6991ed632c4dbf81dc2467f7a77f65e.jpg);\n"
"")
        self.label_37.setText("")
        self.label_37.setPixmap(QtGui.QPixmap(":/newPrefix/photop/e6991ed632c4dbf81dc2467f7a77f65e.jpg"))
        self.label_37.setScaledContents(True)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.groupBox_7)
        self.label_38.setGeometry(QtCore.QRect(200, 220, 201, 161))
        self.label_38.setStyleSheet("background-image:url(:/newPrefix/photop/b2a7dc5ca195f635ce66665b00ae33a0.jpg);")
        self.label_38.setText("")
        self.label_38.setPixmap(QtGui.QPixmap(":/newPrefix/photop/b2a7dc5ca195f635ce66665b00ae33a0.jpg"))
        self.label_38.setScaledContents(True)
        self.label_38.setObjectName("label_38")
        self.textEdit_9 = QtWidgets.QTextEdit(self.tab_10)
        self.textEdit_9.setGeometry(QtCore.QRect(480, 80, 161, 31))
        self.textEdit_9.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.textEdit_9.setStyleSheet("background:none;\n"
"")
        self.textEdit_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textEdit_9.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.textEdit_9.setReadOnly(False)
        self.textEdit_9.setOverwriteMode(False)
        self.textEdit_9.setObjectName("textEdit_9")
        self.textEdit_10 = QtWidgets.QTextEdit(self.tab_10)
        self.textEdit_10.setGeometry(QtCore.QRect(480, 140, 161, 31))
        self.textEdit_10.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.textEdit_10.setStyleSheet("background:none;\n"
"")
        self.textEdit_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textEdit_10.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.textEdit_10.setReadOnly(False)
        self.textEdit_10.setOverwriteMode(False)
        self.textEdit_10.setObjectName("textEdit_10")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_10)
        self.pushButton_5.setGeometry(QtCore.QRect(520, 200, 75, 41))
        self.pushButton_5.setStyleSheet("font: 11pt;\n"
"color: #750000;\n"
"font: bold;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.tabWidget.addTab(self.tab_10, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_11)
        self.groupBox_8.setGeometry(QtCore.QRect(20, 20, 421, 411))
        self.groupBox_8.setStyleSheet("background:none;")
        self.groupBox_8.setObjectName("groupBox_8")
        self.label_39 = QtWidgets.QLabel(self.groupBox_8)
        self.label_39.setGeometry(QtCore.QRect(20, 30, 171, 171))
        self.label_39.setStyleSheet("background-image:url(:/newPrefix/photop/0204b73676cea3cda6b1ba4362a805b7.jpg);")
        self.label_39.setText("")
        self.label_39.setPixmap(QtGui.QPixmap(":/newPrefix/photop/0204b73676cea3cda6b1ba4362a805b7.jpg"))
        self.label_39.setScaledContents(True)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.groupBox_8)
        self.label_40.setGeometry(QtCore.QRect(220, 30, 181, 171))
        self.label_40.setStyleSheet("background-image:url(:/newPrefix/photop/af5318b5fb64d921a2d69969dd576e94.jpg);")
        self.label_40.setText("")
        self.label_40.setPixmap(QtGui.QPixmap(":/newPrefix/photop/8f2b4c2ea900323aec716ee886f7f066.jpg"))
        self.label_40.setScaledContents(True)
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.groupBox_8)
        self.label_41.setGeometry(QtCore.QRect(20, 222, 171, 161))
        self.label_41.setStyleSheet("background-image:url(:/newPrefix/photop/af5318b5fb64d921a2d69969dd576e94.jpg);")
        self.label_41.setText("")
        self.label_41.setPixmap(QtGui.QPixmap(":/newPrefix/photop/af5318b5fb64d921a2d69969dd576e94.jpg"))
        self.label_41.setScaledContents(True)
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.groupBox_8)
        self.label_42.setGeometry(QtCore.QRect(220, 220, 181, 161))
        self.label_42.setStyleSheet("background-image:url(:/newPrefix/photop/0506b06e45ffd601a3c78d71dc708813.jpg);")
        self.label_42.setText("")
        self.label_42.setPixmap(QtGui.QPixmap(":/newPrefix/photop/0506b06e45ffd601a3c78d71dc708813.jpg"))
        self.label_42.setScaledContents(True)
        self.label_42.setObjectName("label_42")
        self.textEdit_11 = QtWidgets.QTextEdit(self.tab_11)
        self.textEdit_11.setGeometry(QtCore.QRect(470, 80, 161, 31))
        self.textEdit_11.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.textEdit_11.setStyleSheet("background:none;\n"
"")
        self.textEdit_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textEdit_11.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.textEdit_11.setReadOnly(False)
        self.textEdit_11.setOverwriteMode(False)
        self.textEdit_11.setObjectName("textEdit_11")
        self.textEdit_12 = QtWidgets.QTextEdit(self.tab_11)
        self.textEdit_12.setGeometry(QtCore.QRect(470, 140, 161, 31))
        self.textEdit_12.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.textEdit_12.setStyleSheet("background:none;\n"
"")
        self.textEdit_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textEdit_12.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.textEdit_12.setReadOnly(False)
        self.textEdit_12.setOverwriteMode(False)
        self.textEdit_12.setObjectName("textEdit_12")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_11)
        self.pushButton_6.setGeometry(QtCore.QRect(510, 200, 75, 41))
        self.pushButton_6.setStyleSheet("font: 11pt;\n"
"color: #750000;\n"
"font: bold;")
        self.pushButton_6.setObjectName("pushButton_6")
        self.tabWidget.addTab(self.tab_11, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_12)
        self.groupBox_9.setGeometry(QtCore.QRect(30, 10, 641, 411))
        self.groupBox_9.setStyleSheet("background:none;")
        self.groupBox_9.setObjectName("groupBox_9")
        self.label_43 = QtWidgets.QLabel(self.groupBox_9)
        self.label_43.setGeometry(QtCore.QRect(490, 30, 131, 121))
        self.label_43.setStyleSheet("background-image:url(:/newPrefix/photop/SunvenoRockingDinosaurwithWheels_2_360x.jpg);")
        self.label_43.setText("")
        self.label_43.setPixmap(QtGui.QPixmap(":/newPrefix/photop/SunvenoRockingDinosaurwithWheels_2_360x.jpg"))
        self.label_43.setScaledContents(True)
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.groupBox_9)
        self.label_44.setGeometry(QtCore.QRect(340, 30, 131, 121))
        self.label_44.setStyleSheet("background-image:url(:/newPrefix/photop/357256fdd033776a3310589392ad788d.jpg)")
        self.label_44.setText("")
        self.label_44.setPixmap(QtGui.QPixmap(":/newPrefix/photop/357256fdd033776a3310589392ad788d.jpg"))
        self.label_44.setScaledContents(True)
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.groupBox_9)
        self.label_45.setGeometry(QtCore.QRect(180, 30, 141, 121))
        self.label_45.setStyleSheet("background-image:url(:/newPrefix/photop/20565b94500e4e484e742f9b279e78a0.jpg);")
        self.label_45.setText("")
        self.label_45.setPixmap(QtGui.QPixmap(":/newPrefix/photop/20565b94500e4e484e742f9b279e78a0.jpg"))
        self.label_45.setScaledContents(True)
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.groupBox_9)
        self.label_46.setGeometry(QtCore.QRect(430, 190, 161, 151))
        self.label_46.setStyleSheet("background-image:url(:/newPrefix/photop/cb8fe639a69b4cb2f6a0fcd703ecd697.jpg);")
        self.label_46.setText("")
        self.label_46.setPixmap(QtGui.QPixmap(":/newPrefix/photop/cb8fe639a69b4cb2f6a0fcd703ecd697.jpg"))
        self.label_46.setScaledContents(True)
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.groupBox_9)
        self.label_47.setGeometry(QtCore.QRect(250, 190, 161, 151))
        self.label_47.setStyleSheet("background-image:url(:/newPrefix/photop/SunvenoBasketballFootballSoccerandGolfSet_9_360x.jpg);")
        self.label_47.setText("")
        self.label_47.setPixmap(QtGui.QPixmap(":/newPrefix/photop/SunvenoBasketballFootballSoccerandGolfSet_9_360x.jpg"))
        self.label_47.setScaledContents(True)
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.groupBox_9)
        self.label_48.setGeometry(QtCore.QRect(60, 190, 171, 151))
        self.label_48.setStyleSheet("background-image:url(:/newPrefix/photop/b75efe91a0d2a9af4cee7577e992464d.jpg);")
        self.label_48.setText("")
        self.label_48.setPixmap(QtGui.QPixmap(":/newPrefix/photop/b75efe91a0d2a9af4cee7577e992464d.jpg"))
        self.label_48.setScaledContents(True)
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.groupBox_9)
        self.label_49.setGeometry(QtCore.QRect(20, 30, 141, 121))
        self.label_49.setStyleSheet("background-image:url(:/newPrefix/photop/51DNmPdYNzL_1024x1024_900d4108-e726-41e8-ac3c-08b00c64dd75_360x.jpg);")
        self.label_49.setText("")
        self.label_49.setPixmap(QtGui.QPixmap(":/newPrefix/photop/51DNmPdYNzL_1024x1024_900d4108-e726-41e8-ac3c-08b00c64dd75_360x.jpg"))
        self.label_49.setScaledContents(True)
        self.label_49.setObjectName("label_49")
        self.tabWidget.addTab(self.tab_12, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 734, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_33.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#ffffff;\">مرحبا بكم في عالم القهوة</span></p></body></html>"))
        self.label_34.setText(_translate("MainWindow", "هنا تجد كل ما يلائم طفلك.."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("MainWindow", "الرئيسية"))
        self.groupBox_7.setTitle(_translate("MainWindow", "ملابس البنات"))
        self.textEdit_9.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Dubai\'; font-size:9pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"right\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_9.setPlaceholderText(_translate("MainWindow", "الــعــمــر"))
        self.textEdit_10.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Dubai\'; font-size:9pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"right\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_10.setPlaceholderText(_translate("MainWindow", "الـقـيـاس"))
        self.pushButton_5.setText(_translate("MainWindow", "موافق"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_10), _translate("MainWindow", "قسم البنات"))
        self.groupBox_8.setTitle(_translate("MainWindow", "ملابس الاولاد"))
        self.textEdit_11.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Dubai\'; font-size:9pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"right\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_11.setPlaceholderText(_translate("MainWindow", "الــعــمــر"))
        self.textEdit_12.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Dubai\'; font-size:9pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"right\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_12.setPlaceholderText(_translate("MainWindow", "الـقـيـاس"))
        self.pushButton_6.setText(_translate("MainWindow", "موافق"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_11), _translate("MainWindow", "قسم الاولاد"))
        self.groupBox_9.setTitle(_translate("MainWindow", "العاب"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_12), _translate("MainWindow", "الالعاب"))
import image_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
